In [1]:
import numpy as np

1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [2]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0

2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [3]:
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1

либо

In [4]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1

3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [5]:
x = np.diag([1, 2, 3, 4, 5], k=-1)

4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [6]:
x= np.random.random((5,5))
means=np.mean(x,axis=1)
x-=means[:,np.newaxis]
x

array([[-0.25329287, -0.16317268, -0.10242616,  0.38747347,  0.13141824],
       [ 0.12455461,  0.35245339, -0.17355483, -0.38050392,  0.07705075],
       [-0.13054465, -0.08985711,  0.10359346,  0.41103403, -0.29422573],
       [-0.17859308,  0.09435409, -0.06685285, -0.00222787,  0.15331972],
       [ 0.08268801,  0.41666691, -0.48087863,  0.12746588, -0.14594217]])

5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [7]:
x= np.random.random((10,3))
print(x)
x_=np.argmin(abs(x-0.5), axis=1)
print(x_)
print(x[np.arange(10),x_])

[[0.94350398 0.05079383 0.54331335]
 [0.56648292 0.45087153 0.95983633]
 [0.8596015  0.81937474 0.10883647]
 [0.43367952 0.56665968 0.39081543]
 [0.04900822 0.83492108 0.19203254]
 [0.11415273 0.19327573 0.53728377]
 [0.41630722 0.2381976  0.19067246]
 [0.0776169  0.44348448 0.69199899]
 [0.46399195 0.89729076 0.52825617]
 [0.79617439 0.93982998 0.01126856]]
[2 1 1 0 2 2 0 1 2 0]
[0.54331335 0.45087153 0.81937474 0.43367952 0.19203254 0.53728377
 0.41630722 0.44348448 0.52825617 0.79617439]


6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [8]:
x= np.random.random((6,6))
print(x)
sum=np.sum(x,axis=1)
max=np.max(x,axis=0)
a=sum/max
a

[[0.87450718 0.82329337 0.16509082 0.90466802 0.71815482 0.69639868]
 [0.87250499 0.91700893 0.27244444 0.76819611 0.77288528 0.39412334]
 [0.21741304 0.88882362 0.23295502 0.84922617 0.81041872 0.06118916]
 [0.86686338 0.08667131 0.52244535 0.4007476  0.76402945 0.53598301]
 [0.37291307 0.97834076 0.76146646 0.57375338 0.55276603 0.74037995]
 [0.68019741 0.77006548 0.90934703 0.34682898 0.62456482 0.60291117]]


array([4.78225109, 4.08565528, 3.36508027, 3.51149817, 4.9105722 ,
       5.31337307])

7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [17]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
a=np.where(x[:-1]==0)[0]
print(np.max(x[a+1]))

5


8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [32]:
x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
a, count=np.unique(i,return_counts=True)
x[a]+=count
x-1

array([1., 1., 1., 1., 0., 3., 0., 0., 1., 0.])