In [2]:
import numpy as np

1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [4]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0

2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [5]:
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1

либо

In [6]:
x = np.zeros((8,8), dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1

3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [8]:
x = np.diag([1, 2, 3, 4, 5], k=-1)

4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.

In [9]:
x= np.random.random((5,5))
for i in range(0,5):
    x[i]=x[i]-sum(x[i])/5

5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [17]:
x= np.random.random((10,3))
print(x)
for i in range(0,10):
    print(x[i][abs(x[i]-0.5)==min(abs(x[i]-0.5))])

[[0.01613051 0.23401356 0.41306578]
 [0.73240892 0.4456062  0.79112099]
 [0.58494109 0.23836321 0.13024867]
 [0.44577492 0.53394599 0.16470184]
 [0.55193202 0.0860752  0.59559889]
 [0.99551601 0.84118938 0.36718911]
 [0.60815679 0.97564143 0.14128997]
 [0.4983617  0.60248304 0.12873777]
 [0.27317317 0.07019396 0.90933781]
 [0.01718676 0.55189418 0.16195326]]
[0.41306578]
[0.4456062]
[0.58494109]
[0.53394599]
[0.55193202]
[0.36718911]
[0.60815679]
[0.4983617]
[0.27317317]
[0.55189418]


6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [18]:
x= np.random.random((6,6))
print(x)
for i in range(0,6):
    print(sum(x[i])/max(x[:,i]))

[[0.16172808 0.0264145  0.32323552 0.10764886 0.08900682 0.53669256]
 [0.39377632 0.5347253  0.29682583 0.86509936 0.80207456 0.83862425]
 [0.81612519 0.48945274 0.0694763  0.07296862 0.75291225 0.60031984]
 [0.99964575 0.07722105 0.84232057 0.48759343 0.13504364 0.06853878]
 [0.70882321 0.96454107 0.63061398 0.71672655 0.60635966 0.8790501 ]
 [0.35713545 0.63644222 0.23646024 0.59681423 0.93462219 0.03766773]]
1.2451674496388263
3.86829108499333
3.325639942376495
3.017414342768312
4.821322021198686
3.1842804803791043


7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [23]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max(x[1:][(x==0)[:-1]]))

5


8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [28]:
x = np.ones(10) 
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j]+=1